# to validate any changes
# use:
# circleci config process .circleci/config.yml > config_processed.yml
#
version: 2.1
parameters:
  pr_workflow:    # runs for every pull request.
    type: boolean
    default: true # by default pr workflow will get executed.
  release_workflow:
    type: boolean
    default: false
  releaseCommand:
    type: string
    default: "foo" # when specified this mean the workflow was called from release-tool.
executors:
  generic-executor:
    docker:
      - image: 'circleci/node:latest'
jobs:
  ExecuteRelease:
    executor: generic-executor
    parameters:
      releaseCommand:
        type: string
        default: ""
    steps:
      - checkout # release command builds as part of the flow.
      - run: echo <<pipeline.parameters.releaseCommand>>
      # - run: <<parameters.releaseCommand>>
      #     type: approval
  EchoJob:
    executor: generic-executor
    parameters:
      to:
        type: string
        default: "Hello World"
    steps:
      - run: echo << parameters.to >>
  ExecuteReleaseDummy:
    executor: generic-executor
    steps:
      - run: echo relasecommand = << pipeline.parameters.releaseCommand >>
      - run: echo GH_TOKEN=$GH_TOKEN
      - run: echo NPM_AUTH_TOKEN=$NPM_AUTH_TOKEN


workflows:
  version: 2
  PR_Workflow:
    when: << pipeline.parameters.pr_workflow >>
    jobs:
      - EchoJob:
          to: "This is my placeholder PR job"
  Release_Workflow:
    when: << pipeline.parameters.release_workflow >>
    jobs:
      - hold1:
          type: approval
      - ExecuteReleaseDummy:
          context: sdk_js
          requires: [hold1]
      - hold2:
          type: approval
          requires: [ExecuteReleaseDummy]
      - ExecuteRelease: # this job has conditional steps, no-ops when pipeline.parameters.releaseCommand not specified
          context: sdk_js
          releaseCommand: << pipeline.parameters.releaseCommand >>
          requires: [hold2]
